### PR TITLE
 Adding 1.7, 1.8, 1.9, 1.10, 1.10+ support for (Bedrock Edition)

### PR DESCRIPTION
**Pull request by StealthyExpertX**
Added missing entities.json for 1.7,
Added 1.7/blocks.json for 1.7
Added missing 1.6/blocks.json for 1.6

Updated the mcver.json mcver.json with the 1.7, 1.8, 1.9, 1.10 weblinks.
Updated materials.py with new pocketMaterials #still working on adding more...

NOTE: #1
Do not push this commit until asked so by me please and thank you,

NOTE: #2
This is the start of adding a large scale commit that will add all the blocks, entities, biomes, etc... for the versions listed in this title.

### CODE REVIEW

**Comment by DJthefirst** [comment]
is their any way to add this to the current versiona sa a temp fix im trying to edit my dedicated server for bedrock

**Comment by StealthyExpertX** [comment]
Not yet, I'm working on getting MCEdit updated for the community so sad seeing it so out of date.

**Comment by OnlyBMan** [comment]
I'm so glad to see you do all this @StealthyExpertX nice job! I was really disappointed when I saw the project became inactive.

**Comment by gabefair** [comment]
Thank you again for doing this. Microsoft has updated Minecraft BE to version 1.16.1, I will now test your code with this version.

**Comment by StealthyExpertX** [comment]
This was abandoned due to support breaking Mcedit. We'll take down the push
very soon sorry to disappoint.

**Pull request closed without merging**
