### PR TITLE
Added Java 1.12 Bed TileEntity Support, Fixed PE 2x Fence Block Bugs, Added 6x PE Entity Definitions To entities.json

### PR DESCRIPTION
**Pull request by StealthyExpertX**
Updated and added bed tileentity handling to entity.py at path
\MCEdit-Unified\pymcleve\entity.py

image
image
image
image

Added 1.12 Java tileentities.json at path
\MCEdit-Unified\mcver\1.12\tileentities.json

image

Working example of bed tileentity support tested using the fill tool.

image

Updated PE Entity definitions with 6x more (Entities) entities.json at path
\MCEdit-Unified\mcver\PE\entities.json

image
image
image

Fixed Two Bugs In PE Block definitions blocks.json at path
\MCEdit-Unified\mcver\PE\blocks.json

1. Fixed swapped textures acacia fence was rendering as dark oak fence
this has been fixed by updating the texture map by swapping the values.

2. Fixed typo by changing Acasia Fence to Acacia Fence
-                    "name": "Acasia Fence",
+                    "name": "Acacia Fence",

#Bug Fix 1
image

#Bug Fix 2
image

### CODE REVIEW

**Review by LaChal — CHANGES_REQUESTED** [review]
Something went bad in `pmclevel/entity.py`; according Git, the whole file has been changed.

I guess this is due to your editor forcibly changing line ending.

Please, restore the original line ending, so we can know what is changed in the file.

**Comment by StealthyExpertX** [comment]
@LaChal @Podshot I'm not sure how I would be able to do that to be honest with you?

to reset line endings if you need to know what was changed refer to the pictures in the above comment 
I showed where I edited or added code.

if you could further explain to me how to reset the line endings I'd be more than glad to fix that for you.
also what do you mean that pmclevel/entity.py something went bad here?
do you mean with the line ending or do you mean with the code itself if so that's very weird I was running it before in my test and it ran fine?.

**Comment by LaChal** [comment]
@StealthyExpertX You don't need to put all lines you changed in the PR message, Github is able to display this :wink:  
  
To see the 'diff', just go to the [Files changed](https://github.com/Podshot/MCEdit-Unified/pull/903/files) tab.  
  
Looking to your screenshots, I think you're using *Notepad++*, so you can display all the characters using an option in the view menu, and change the line endings. (I can't remember which one exactly...)    
  
The line ending issue may also come from your Git client configuration. Please have a look to Git documentation and google a bit to find how to set  your client to preserve original line endings.

**Comment by naor2013** [comment]
I fixed the line ending issue and merged the changes! Thanks a lot @StealthyExpertX 
Great change :)

**Pull request merged**
